### ISSUE TITLE
For your interest

### ISSUE THREAD

**Issue by Lingxi-Li** [iDingDong/libDDCPP#2]
Guess you will like [this](https://github.com/Lingxi-Li/CPP_Utility) :) It's a fun project for interest in writing creative, tricky, yet useful trinkets and extensions to modern C++. Hope you could join the party and play together~

**Comment by iDingDong** [comment]
Sorry about my long overdue rely, cause I've been working with my git-extensions for months. I suspected that nobody would ever take a look on this repo, not to mention submitting an issue.

Anyway, I would really appreciate it if we can share our interest in modern C++, and I would certainly be in the game if you can forgive my indiscretion.
